name: CI/CD for Data Project

on:
  push:
    branches:
      - prd           # Nhánh production
      - dev/**        # Hỗ trợ tất cả các nhánh bắt đầu bằng "dev/"
  pull_request:
    branches:
      - prd           # Kích hoạt khi có pull request vào nhánh prd

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Python Environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Hoặc phiên bản Python bạn sử dụng

      # 3. Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # File chứa các thư viện của dự án

      # 4. Linting và Kiểm tra Code
      - name: Run Linting
        run: |
          flake8 .  # Kiểm tra lỗi code với flake8
      - name: Run Unit Tests
        run: |
          pytest tests/  # Chạy test bằng pytest

  dbt:
    name: DBT Model Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Cài đặt DBT
      - name: Install DBT
        run: |
          pip install dbt-core dbt-spark  # Hoặc plugin DBT cho Spark

      # Validate DBT Models
      - name: Validate DBT Models
        run: |
          dbt debug
          dbt run --models state:modified  # Chạy các model đã thay đổi

  airflow:
    name: Airflow DAG Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Cài đặt Airflow
      - name: Install Airflow
        run: |
          pip install apache-airflow

      # Validate DAGs
      - name: Validate DAGs
        run: |
          airflow dags list  # Kiểm tra danh sách DAGs
          airflow dags test my_dag 2024-11-19  # Kiểm tra DAG cụ thể
