name: Pull Request CI

on:
  pull_request:
    branches:
      - prod           # Kích hoạt khi tạo PR vào nhánh chính là `prod`
    paths-ignore:
      - README.md      # (Tùy chọn) Bỏ qua PR nếu chỉ thay đổi các file không liên quan

jobs:
  lint_and_test:
    name: Lint and Test Code
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Setup Python Environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run Linting
      - name: Lint Code with flake8
        run: |
          flake8 .

      # 5. (Tùy chọn) Run Unit Tests nếu thư mục `tests/` tồn tại
      - name: Run Unit Tests
        run: |
          if [ -d "tests" ]; then pytest tests/; else echo "No tests found, skipping."; fi

  approve:
    name: Require Manual Approval
    runs-on: ubuntu-latest
    needs: lint_and_test
    steps:
      - name: Wait for Review
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
