name: Pull Request CI

on:
  pull_request_target:
    branches:
      - prod
    paths-ignore:
      - README.md

jobs:
  lint_python:
    name: Lint Python Code
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Install Python Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 3. Lint Python Files
      - name: Lint Python Files
        if: contains(github.event.pull_request.changed_files, '.py')
        run: |
          flake8 .

  test_dbt:
    name: Test DBT Models
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Install DBT
      - name: Install DBT
        run: |
          python -m pip install dbt-core dbt-postgres

      # 3. Validate DBT Files
      - name: Validate DBT Models
        if: contains(github.event.pull_request.changed_files, '.sql') || contains(github.event.pull_request.changed_files, '.yml')
        run: |
          dbt deps
          dbt compile
          dbt test

  test_airflow:
    name: Test Airflow DAGs
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Install Airflow
      - name: Install Airflow
        run: |
          python -m pip install apache-airflow

      # 3. Validate Airflow DAGs
      - name: Validate Airflow DAGs
        if: contains(github.event.pull_request.changed_files, 'dags/')
        run: |
          airflow dags list
